[project]
name = "trace"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "autogen>=0.9.7",
    "ipykernel>=6.31.0",
    "openai>=2.8.1",
    "trace-opt[autogen]>=0.1.3.8",
]
